### PR TITLE
#97 Fixes the dialog box not showing up when the server is full

### LINKED ISSUE #97: No dialog indicating server has maximum amount of players
When someone conects to a full server, it just fails, doesn't tell you it is full.

### PR DESCRIPTION
**Pull request by Cameron-Friel**
Fixes #97

### CODE REVIEW

File: Source/Client/MultiplayerSession.cs [hunk 1]
```diff
@@ -168,6 +168,9 @@ public void Disconnected()
             if (disconnectReason == MpDisconnectReason.Defs) {
                 Find.WindowStack.Add(new DefMismatchWindow(mods));
             }
+            else if (disconnectReason == MpDisconnectReason.ServerFull) {
+                Find.WindowStack.Add(new DisconnectedWindow(disconnectReasonKey, disconnectInfo));
+            }
```
Comment (Nebual) [inline Source/Client/MultiplayerSession.cs:173]: Oh yeah this one, I glanced at this code and couldn't figure out why the `else {}` wouldn't have handled this fine. Any idea?

Comment (Cameron-Friel) [reply Source/Client/MultiplayerSession.cs:173]: I believe so. The dialog box wasn't showing up because `Multiplayer.Client.State` was giving back a null reference for the server full case in the else statement. I think it was never initialized since the connection is rejected here `req.Reject(IConnection.GetDisconnectBytes(MpDisconnectReason.ServerFull));`  in  MultiplayerServer.cs; where as the other cases are closed via the `disconnect()` function found in ServerConnection.cs.

**Comment by notfood** [comment]
My bad, merged to master. Fixed manually.
